### ISSUE TITLE
OpenML / wandb always need to be both installed

### ISSUE THREAD

**Issue by dunnkers** [dunnkers/fseval#46]
```shell
(fseval-readme-example) ➜  fseval-readme-example python somebenchmark.py --help
Traceback (most recent call last):
  File "/Users/dunnkers/git/fseval-readme-example/somebenchmark.py", line 4, in <module>
    from fseval.adapters import OpenML
  File "/Users/dunnkers/git/fseval/fseval/adapters/__init__.py", line 2, in <module>
    from .wandb import Wandb
  File "/Users/dunnkers/git/fseval/fseval/adapters/wandb.py", line 4, in <module>
    import wandb
ModuleNotFoundError: No module named 'wandb'
```

Because we are always importing **both** modules:
https://github.com/dunnkers/fseval/blob/a52fdad8b1513b6c7a3e56fb588ea755c0d32b4b/fseval/adapters/__init__.py#L1-L4

**Comment by dunnkers** [comment]
+same for storage module
